version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: meu-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME:   # Defina um usuário (opcional)
      MONGO_INITDB_ROOT_PASSWORD:   # Defina uma senha (opcional)
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
