# Usa a imagem oficial do MongoDB
FROM mongo:latest

# Define a porta padrão do MongoDB
EXPOSE 27017

# Define um diretório para armazenar os dados do MongoDB
VOLUME /data/db

# Comando padrão para iniciar o MongoDB
CMD ["mongod"]

